openapi: 3.0.0
info:
  title: Ruby Backend Dev Challenge API
  version: 1.0.0
paths:
  /auth:
    post:
      summary: Authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token returned
  /products:
    post:
      summary: Create product (async)
      responses:
        '202':
          description: Product creation scheduled
    get:
      summary: List products
      responses:
        '200':
          description: List of products
  /products/{id}:
    get:
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product found
        '404':
          description: Not found